version: 2.1

jobs:
  build:
    docker:
      - image: docker
    steps:
      - run: 
          name: Current working directory
          command: echo $(pwd)
      - run: 
          name: Test docker is available
          command: docker --version
      - setup_remote_docker
      - run:
          name: Test remote docker is working
          command: docker info
      - run:
          name: Run docker hello-world
          command: docker run hello-world
      - run:
          name: See docker hello-world image
          command: docker image ls
      - run:
          name: See docker container that ran the hello-world image
          command: docker container ls --all
      - checkout
      - run:
          name: See the code
          command: ls -a