version: 2.1

jobs:
  build:
    docker:
      - image: alpine:3.8
    steps:
      - checkout
      - run: echo $(pwd)
      - run:
          name: Install docker
          command: |
            apk update
            apk add docker
      - run: docker --version
      - run: 
          name: Run docker
          command: |
            service docker start
            #docker run --name alpine-docker -p 2375:2375 --privileged -d danielguerra/alpine-docker
            #docker run hello-world