version: 2.1

jobs:
  build:
    docker:
      - image: docker
    steps:
      - checkout
      - run: 
          name: Current working directory
          command: echo $(pwd)
      - run: 
          name: Test docker is available
          command: docker --version
      - setup_remote_docker
      - run:
          name: Test remote docker is on
          command: docker info
      - run:
          name: Run hello docker
          command: |
            docker run hello-world

            echo "Docker Images"
            docker image ls

            echo "Docker Containers"
            docker container ls --all