version: 2.1

jobs:
    test-docker:
        docker:
        - image: docker:18.09
        steps:
        - run: 
            name: Test docker is available
            command: docker --version
        - setup_remote_docker
        - run:
            name: Test remote docker is working
            command: docker info
        - run:
            name: Run docker hello-world
            command: docker run hello-world
        - run:
            name: See docker hello-world image
            command: docker image ls
        - run:
            name: See docker container that ran the hello-world image
            command: docker container ls --all
    build-docker-image:
        docker:
        - image: docker
        steps:
        - setup_remote_docker
        - checkout
        - run:
            name: Show current working directory
            command: |
                echo $(pwd)
                ls -a
        - run:
            name: Build docker image
            command: |
                docker build -t friendlyhello .
                docker image ls
        - run:
            name: Test run the image
            command: |
                # map port 4000 to the exposed port 80 (see Dockerfile)
                docker run -d -p 8080:8080 --name friendlyhello friendlyhello
                # test the app in running
                # use the exposed port 8080 since curl is run inside the container
                docker exec friendlyhello curl --retry 10 --retry-connrefused http://localhost:8080
        - run:
            name: Login to my docker hub
            command: |
                set -o nounset
                # login my docker hub account
                docker login --username "$DOCKER_USERNAME" --password "$DOCKER_PASSWORD"
                # tag latest image
                docker tag friendlyhello phucknguyen/friendlyhello
                # push latest image
                docker push phucknguyen/friendlyhello

    test-image-pushed:
        docker:
        - image: byrnedo/alpine-curl
        - image: phucknguyen/friendlyhello:0.0.2
        steps:
        - run:
            name: Test the app is run inside container
            command: |
                # ls /app/
                # cd /app/
                # python app.py
                curl --retry 10 --retry-connrefused http://localhost:80 || echo "80 failed"
                curl --retry 10 --retry-connrefused http://localhost:4000 || echo "4000 failed"

workflows:
    version: 2
    test-and-build:
        jobs:
        - test-docker
        - build-docker-image:
            requires:
                - test-docker
        - test-image-pushed