version: 2.1

jobs:
  build:
    docker:
      - image: danielguerra/alpine-docker
    steps:
      - checkout
      - run: echo $(pwd)
      - run: docker --version
      - run: 
          name: Run docker
          command: |
            dockerd
            #docker run --name alpine-docker -p 2375:2375 --privileged -d danielguerra/alpine-docker
            #docker run hello-world