version: 2.1

jobs:
  build:
    docker:
      - image: alpine:3.8
    steps:
      - checkout
      - run: 
          name: Current working directory
          command: echo $(pwd)
      - run:
          name: Update package index
          command: apk update
      - run:
          name: Install required commands 
          command: |
            apk add openrc # openrc includes service
            apk add shadow # shadow includes usermod
      - run: 
          name: Install docker
          command: |
            apk add docker
            docker --version
      - run:
          name: Allow to run docker
          command: |
            # add current user to docker group
            usermod -aG docker $(whoami)
            service docker stop
            # service docker start
            service docker start
      - run:
          name: Run docker hello-world
          command: docker run hello-world