version: 2.1

jobs:
  build:
    docker:
      - image: docker
    steps:
      - checkout
      - run: 
          name: Current working directory
          command: echo $(pwd)
      - run: 
          name: Test docker is installed
          command: docker --version
      - setup_remote_docker
      - run:
          name: Test remote docker is on
          command: docker container ls
      - run:
          name: Hello docker
          command: docker run hello-world