version: 2.1

jobs:
  build:
    docker:
      - image: alpine:3.8
    steps:
      - checkout
      - run: 
          name: Current working directory
          command: echo $(pwd)
      - run:
          name: Update package index
          command: apk update
      - run:
          name: Install docker and related packages
          command: |
            apk add docker
            apk add openrc # openrc includes service
            apk add shadow # shadow includes usermod
      - run: 
          name: Is docker installed?
          command: docker --version
      - run: 
          name: Run docker
          command: |
            # add current user to docker group
            usermod -aG docker $(whoami)
            # service docker stop
            # service docker start
            docker run hello-world