version: 2.1

jobs:
  build:
    docker:
      - image: alpine:3.8
    steps:
      - checkout
      - run: 
          name: Current working directory
          command: echo $(pwd)
      - setup_remote_docker
      - run: 
          name: Try docker
          command: |
            docker --version
            docker container ls
      # - run:
      #     name: Run docker hello-world
      #     command: docker run hello-world